name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Golang
      uses: actions/setup-go@v3
      with:
        go-version: '^1.18.3'
        cache: true
    - name: Test
      run: go test
    - name: Archive
      uses: actions/upload-artifact@v3
      with:
        name: statusline
        path: statusline
