name: Release Candidate

on:
  push:
    branches:
      - master
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Golang
      uses: actions/setup-go@v3
      with:
        go-version: '^1.18.3'
        cache: true
    - name: Build
      run: go build
    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: latest
        prerelease: "${{ !startsWith(github.ref, 'refs/tags/') }}"
        files: |
          statusline
